using System.IO;
using System.Linq;
using System.Text;
using UnityEditor;
using UnityEngine;

namespace Ripple.Editor
{
    public static class RippleCodegenRunner
    {
        [MenuItem("Tools/Ripple/Regenerate Typed Subclasses")]
        public static void Regenerate()
        {
            var configs = AssetDatabase.FindAssets("t:" + nameof(RippleCodegenConfig));
            if (configs.Length == 0)
            {
                Debug.LogWarning("[Ripple] No RippleCodegenConfig found. Create one via Assets/Create/Ripple/Codegen Config.");
                return;
            }
            var path = AssetDatabase.GUIDToAssetPath(configs[0]);
            var config = AssetDatabase.LoadAssetAtPath<RippleCodegenConfig>(path);
            Generate(config);
        }

        public static void Generate(RippleCodegenConfig config)
        {
            if (config == null) return;
            var outDir = config.OutputDirectory;
            if (!Directory.Exists(outDir)) Directory.CreateDirectory(outDir);

            int written = 0;
            foreach (var row in config.Rows)
            {
                written += Write(outDir, row.TypeName + "Event.Generated.cs", BuildEvent(row));
                written += Write(outDir, row.TypeName + "VariableSO.Generated.cs", BuildVariable(row));
            }
            written += Write(outDir, "References.Generated.cs", BuildReferencesAggregate(config));
            written += Write(outDir, "EventListeners.Generated.cs", BuildEventListenersAggregate(config));
            written += Write(outDir, "VariableListeners.Generated.cs", BuildVariableListenersAggregate(config));

            AssetDatabase.Refresh();
            Debug.Log($"[Ripple] Codegen wrote/updated {written} file(s).");
        }

        private static int Write(string dir, string file, string contents)
        {
            var path = Path.Combine(dir, file).Replace("\\", "/");
            if (File.Exists(path) && File.ReadAllText(path) == contents) return 0;
            File.WriteAllText(path, contents);
            return 1;
        }

        private static string BuildEvent(RippleCodegenConfig.Row r)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();
            sb.AppendLine("namespace Ripple");
            sb.AppendLine("{");
            sb.AppendLine("    [Preserve]");
            sb.AppendLine("    [RippleData(\"Events\")]");
            sb.AppendLine($"    [CreateAssetMenu(menuName = \"Ripple/Events/{r.DisplayName}\", fileName = \"{r.TypeName}Event\")]");
            sb.AppendLine($"    public sealed class {r.TypeName}Event : GameEvent<{r.CSharpType}> {{ }}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildVariable(RippleCodegenConfig.Row r)
        {
            var ifaces = new System.Collections.Generic.List<string>();
            if (r.IsNumeric) ifaces.Add("INumericVariable");
            if (r.IsComparable) ifaces.Add("IComparableVariable");
            if (r.IsDisplayable) ifaces.Add("IDisplayableVariable");
            var ifaceClause = ifaces.Count > 0 ? ", " + string.Join(", ", ifaces) : "";

            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();
            sb.AppendLine("namespace Ripple");
            sb.AppendLine("{");
            sb.AppendLine("    [Preserve]");
            sb.AppendLine("    [RippleData(\"Variables\")]");
            sb.AppendLine($"    [CreateAssetMenu(menuName = \"Ripple/Variables/{r.DisplayName}\", fileName = \"{r.TypeName}Variable\")]");
            sb.AppendLine($"    public sealed class {r.TypeName}VariableSO : VariableSO<{r.CSharpType}>{ifaceClause}");
            sb.AppendLine("    {");
            if (r.IsNumeric)
            {
                sb.AppendLine("        public double AsDouble => CurrentValue;");
                sb.AppendLine($"        public void SetFromDouble(double value) => SetCurrentValue(({r.CSharpType})value);");
                sb.AppendLine($"        public Type ValueType => typeof({r.CSharpType});");
                sb.AppendLine("        public IDisposable SubscribeNumeric(Action<double> handler) => Subscribe(v => handler((double)v));");
            }
            if (r.IsComparable)
            {
                sb.AppendLine("        public int CompareTo(object other) => other is INumericVariable n ? AsDouble.CompareTo(n.AsDouble) : 0;");
            }
            if (r.IsDisplayable)
            {
                if (r.CSharpType == "string")
                    sb.AppendLine("        public string ToDisplayString(string format) => CurrentValue ?? string.Empty;");
                else if (r.CSharpType.EndsWith("GameObject") || r.CSharpType.EndsWith("Transform"))
                    sb.AppendLine("        public string ToDisplayString(string format) => CurrentValue != null ? CurrentValue.name : \"<null>\";");
                else
                    sb.AppendLine("        public string ToDisplayString(string format) => string.IsNullOrEmpty(format) ? CurrentValue.ToString() : CurrentValue.ToString();");
            }
            sb.AppendLine("    }");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildReferencesAggregate(RippleCodegenConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using System;");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine();
            sb.AppendLine("namespace Ripple");
            sb.AppendLine("{");
            foreach (var r in config.Rows)
                sb.AppendLine($"    [Serializable] public sealed class {r.TypeName}Reference : VariableReference<{r.CSharpType}> {{ public {r.TypeName}Reference() {{ }} public {r.TypeName}Reference({r.CSharpType} v) : base(v) {{ }} }}");
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildEventListenersAggregate(RippleCodegenConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();
            sb.AppendLine("namespace Ripple");
            sb.AppendLine("{");
            foreach (var r in config.Rows)
            {
                sb.AppendLine($"    [Preserve] [AddComponentMenu(\"Ripple/Listeners/{r.DisplayName} Event Listener\")] public sealed class {r.TypeName}EventListener : EventListener<{r.CSharpType}> {{ }}");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }

        private static string BuildVariableListenersAggregate(RippleCodegenConfig config)
        {
            var sb = new StringBuilder();
            sb.AppendLine("// <auto-generated/>");
            sb.AppendLine("using UnityEngine;");
            sb.AppendLine("using UnityEngine.Scripting;");
            sb.AppendLine();
            sb.AppendLine("namespace Ripple");
            sb.AppendLine("{");
            foreach (var r in config.Rows)
            {
                sb.AppendLine($"    [Preserve] [AddComponentMenu(\"Ripple/Listeners/{r.DisplayName} Variable Listener\")] public sealed class {r.TypeName}VariableListener : VariableListener<{r.CSharpType}> {{ }}");
            }
            sb.AppendLine("}");
            return sb.ToString();
        }
    }
}
